# About the site
baseURL = "https://cocky-pare-3da5d5.netlify.app/"
title = "Hugo & Tailwind 3 Template"

# Default Language
languageCode = "en-us"
DefaultContentLanguage = "en"

# Site Settings
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

# Author and Social Details
[params]
  description = "A minimal Hugo template using Tailwind 3 and optimized for SEO."
  author = "Benjamin Price"
  github = "https://github.com/BenjaminPrice"
  facebook = "https://facebook.com/benpricedev"
  og_image = "/images/og.png"
  sitename = "Hugo & Tailwind 3 Template"
  twitter = "@benpricedev"
  # The following should be relative to the root domain or abosolute URL
  favicon = ""
  publisherIcon = "" # Higher resolution version of favicon (Optional)
  articleSections = ['blog', 'posts']

# Language Weights
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  [languages.ja]
    languageName = "Japanese"
    languageCode = "ja"
    weight = 2

# **************************************************************************************
# WARNING: Advanced Users Only Below Here
# You shouldn't need to update these settings unless you're modifying the base template.
# **************************************************************************************

# Template Settings
disableKinds = ["page", "section", "taxonomy", "term", "taxonomyTerm"]

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
  [module.hugoVersion]
    min = "0.93.2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
# Used by PurgeCSS
writeStats = true