[build]
publish = "public"
command = "npm ci && npm run build-tw && hugo --minify --gc -d public;"

[context.production.environment]
HUGO_VERSION = "0.93.2"
NODE_VERSION = "16.14.0"
NODE_ENV = "build"

[context.branch-deploy]
command = "npm ci && npm run build-tw && hugo --minify --gc -d public -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.93.2"
NODE_VERSION = "16.14.0"
NODE_ENV = "build"

[context.deploy-preview]
command = "npm ci && npm run build-tw && hugo --minify --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.93.2"
NODE_VERSION = "16.14.0"
NODE_ENV = "build"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "script-src 'self' 'unsafe-inline'"
